### ISSUE TITLE
Configuring cmake on Linux fails due to missing file, `receiver.h`

### ISSUE THREAD

**Issue by CheesecakeCG** [okawo80085/hobo_vr#37]
The output of 
```bash
mkdir driver/build
cd driver/build
cmake .. -DCMAKE_BUILD_TYPE=Release
```
is
```
-- Configuring done
CMake Error at example/CMakeLists.txt:6 (add_executable):
  Cannot find source file:

    ../src/ref/receiver.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at example/CMakeLists.txt:6 (add_executable):
  No SOURCES given to target: example_receiver


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Also, while this is probably unrelated but, compiling with tests and examples commented out in CMakeList.txt results in [this.](https://gist.github.com/CheesecakeCG/4ddb328d27a7213551e2974f6c492c0d#file-compile_errors-txt) 

CMake 3.19.6 & Clang 11.1.0

**Comment by okawo80085** [comment]
important question, did you run this in `hobo_vr/driver/` or in `hobo_vr/driver/src/`? cuz they have different cmake files in there

you should use the one in `hobo_vr/driver/src/`, it has a readme and everything and it's also the one that works

**Comment by CheesecakeCG** [comment]
I tried both and they both gave the same result.

**Comment by okawo80085** [comment]
k so, i found the problem, the error you're getting is from an old cmake list in `driver/examples`

there is an actual problem with linux version of the driver tho

and that problem is that i split a version of a class into 2 files(1 for windows and 1 for linux), i changed how one worked and forgot the update the other

that class is responsible for socket communication and is kinda critical to to the driver's operation ;^_^

this is an easy fix tho, i'll make a patch shortly

**Comment by okawo80085** [comment]
done, also as a bonus you got c++ bindings for posers, not sure if you'd even need that but still
